### ISSUE TITLE
Add method addTarget

### ISSUE THREAD

**Issue by Vitaliyy-jomedia** [antoniocasero/ACPDownload#1]
Thank you for a wonderful ingredient.
But there is a caveat - there is no method "addTarget".
Do you plan to add it?

**Comment by antoniocasero** [comment]
Yep, there is not addTarget method, I will add it soon. In the meantime, you can use the block solution built in, ACPViewTappedBlock. A block code executed when you tap the view. 

Thanks!

**Comment by Vitaliyy-jomedia** [comment]
I solved this problem as follows:

UITapGestureRecognizer *singleFingerTap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(doHeaderDownloadAction:)];
            [_downloadView addGestureRecognizer:singleFingerTap];
- (void)handleSingleTap:(UITapGestureRecognizer *)recognizer {
  CGPoint location = [recognizer locationInView:[recognizer.view superview]];
  self.downloadView.frame = CGRectMake(location.x,location.y,50,50);
  }
